
# Sources
HOP

# Errors
```bash
D:\anaconda\envs\HOP\python.exe E:\HOP\msg_code\train.py 2024-12-09 14:19:47,072 WARNING deprecation.py:46 -- DeprecationWarning: `ray.rllib.utils.torch_ops.[...]` has been deprecated. Use `ray.rllib.utils.torch_utils.[...]` instead. This will raise an error in the future! 2024-12-09 14:19:56,367 INFO services.py:1340 -- View the Ray dashboard at http://127.0.0.1:8265 2024-12-09 14:20:07,246 WARNING logger.py:326 -- Could not instantiate JsonLogger: Circular reference detected. 2024-12-09 14:20:07,298 INFO trainer.py:745 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags. 2024-12-09 14:20:07,557 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:07,633 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:07,705 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:07,792 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:08,315 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:08,477 WARNING deprecation.py:46 -- DeprecationWarning: `convert_to_non_torch_type` has been deprecated. Use `ray/rllib/utils/numpy.py::convert_to_numpy` instead. This will raise an error in the future! 2024-12-09 14:20:08,555 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:08,618 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:08,686 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:08,754 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:08,820 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:08,878 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:08,938 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:09,006 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:09,069 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:09,134 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:09,203 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! 2024-12-09 14:20:09,333 WARNING util.py:57 -- Install gputil for GPU system monitoring. D:\anaconda\envs\HOP\lib\site-packages\numpy\core\_methods.py:179: RuntimeWarning: overflow encountered in reduce ret = umr_sum(arr, axis, dtype, out, keepdims, where=where) pid=208812) 2024-12-09 14:20:14,883 WARNING deprecation.py:46 -- DeprecationWarning: `ray.rllib.utils.torch_ops.[...]` has been deprecated. Use `ray.rllib.utils.torch_utils.[...]` instead. This will raise an error in the future! pid=16000) 2024-12-09 14:20:14,774 WARNING deprecation.py:46 -- DeprecationWarning: `ray.rllib.utils.torch_ops.[...]` has been deprecated. Use `ray.rllib.utils.torch_utils.[...]` instead. This will raise an error in the future! pid=206356) 2024-12-09 14:20:14,840 WARNING deprecation.py:46 -- DeprecationWarning: `ray.rllib.utils.torch_ops.[...]` has been deprecated. Use `ray.rllib.utils.torch_utils.[...]` instead. This will raise an error in the future! pid=208388) 2024-12-09 14:20:14,911 WARNING deprecation.py:46 -- DeprecationWarning: `ray.rllib.utils.torch_ops.[...]` has been deprecated. Use `ray.rllib.utils.torch_utils.[...]` instead. This will raise an error in the future! pid=14156) 2024-12-09 14:20:14,914 WARNING deprecation.py:46 -- DeprecationWarning: `ray.rllib.utils.torch_ops.[...]` has been deprecated. Use `ray.rllib.utils.torch_utils.[...]` instead. This will raise an error in the future! pid=209800) 2024-12-09 14:20:14,983 WARNING deprecation.py:46 -- DeprecationWarning: `ray.rllib.utils.torch_ops.[...]` has been deprecated. Use `ray.rllib.utils.torch_utils.[...]` instead. This will raise an error in the future! pid=205948) 2024-12-09 14:20:14,999 WARNING deprecation.py:46 -- DeprecationWarning: `ray.rllib.utils.torch_ops.[...]` has been deprecated. Use `ray.rllib.utils.torch_utils.[...]` instead. This will raise an error in the future! pid=20100) 2024-12-09 14:20:14,983 WARNING deprecation.py:46 -- DeprecationWarning: `ray.rllib.utils.torch_ops.[...]` has been deprecated. Use `ray.rllib.utils.torch_utils.[...]` instead. This will raise an error in the future! pid=208812) 2024-12-09 14:20:16,685 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:16,590 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:16,662 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:16,694 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:16,699 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:16,725 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:16,740 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:16,810 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:16,782 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:16,870 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:16,822 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:16,786 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:16,880 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:16,797 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:16,888 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:16,778 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:16,865 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:16,857 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:16,773 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:16,860 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:16,913 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:17,001 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:16,959 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:16,980 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:16,970 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:16,961 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:16,953 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:17,034 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:16,945 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:17,031 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:17,056 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:17,111 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:17,424 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:17,457 WARNING deprecation.py:46 -- DeprecationWarning: `convert_to_non_torch_type` has been deprecated. Use `ray/rllib/utils/numpy.py::convert_to_numpy` instead. This will raise an error in the future! pid=208388) 2024-12-09 14:20:17,572 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:17,561 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:17,508 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:17,570 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:17,627 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:17,582 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:17,574 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:17,609 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:17,643 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:17,648 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:17,659 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:17,670 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:17,652 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:17,753 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:17,732 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:17,805 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:17,728 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:17,793 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:17,746 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:17,819 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:17,758 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:17,741 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:17,812 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:17,715 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:17,812 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:17,717 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:17,790 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:17,829 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:17,834 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:17,869 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:17,866 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:17,927 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:18,009 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:17,897 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:17,987 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:17,951 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:18,033 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:17,912 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:17,997 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:17,910 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:18,004 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:17,904 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:17,989 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:17,897 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:17,983 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:17,961 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:18,043 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:18,072 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:18,069 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:18,078 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:18,090 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:18,083 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:18,090 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:18,123 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:18,127 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:18,191 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:18,278 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:18,161 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:18,264 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:18,224 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:18,184 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:18,188 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:18,161 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:18,266 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:18,184 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:18,222 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:18,282 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:18,282 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:18,289 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:18,376 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:18,351 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:18,425 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) 2024-12-09 14:20:18,331 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:18,377 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:18,382 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:18,362 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:18,434 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:18,375 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:18,331 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:18,409 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:18,478 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:18,478 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:18,482 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:18,476 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:18,478 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208812) 2024-12-09 14:20:18,505 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=14156) 2024-12-09 14:20:18,512 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=208388) 2024-12-09 14:20:18,565 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=206356) 2024-12-09 14:20:18,567 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:18,573 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=209800) 2024-12-09 14:20:18,656 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:18,569 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:18,646 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=20100) 2024-12-09 14:20:18,569 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=205948) 2024-12-09 14:20:18,728 WARNING catalog.py:545 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']! pid=16000) D:\anaconda\envs\HOP\lib\site-packages\numpy\core\_methods.py:179: RuntimeWarning: overflow encountered in reduce pid=16000) ret = umr_sum(arr, axis, dtype, out, keepdims, where=where) 2024-12-09 14:20:48,254 ERROR worker.py:85 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::RolloutWorker.set_weights() (pid=208388, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001D3D9F815C8>) File "python\ray\_raylet.pyx", line 585, in ray._raylet.execute_task File "D:\anaconda\envs\HOP\lib\site-packages\ray\_private\memory_monitor.py", line 158, in raise_if_low_memory self.error_threshold)) ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node LAPTOP-8F8GNOLG is used (15.79 / 15.86 GB). The top 10 memory consumers are: PID MEM COMMAND 22468 1.73GiB D:\pycharm\PyCharm 2023.2.4\bin\pycharm64.exe E:\HOP 118016 0.77GiB D:\anaconda\envs\HOP\python.exe E:\HOP\msg_code\train.py 209800 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 16000 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 206356 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 205948 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 14156 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 20100 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208388 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208812 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py In addition, up to 0.0 GiB of shared memory is currently being used by the Ray object store. --- --- Tip: Use the `ray memory` command to list active objects in the cluster. --- To disable OOM exceptions, set RAY_DISABLE_MEMORY_MONITOR=1. --- 2024-12-09 14:20:48,254 ERROR worker.py:85 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::RolloutWorker.set_weights() (pid=16000, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000029F209B2488>) File "python\ray\_raylet.pyx", line 585, in ray._raylet.execute_task File "D:\anaconda\envs\HOP\lib\site-packages\ray\_private\memory_monitor.py", line 158, in raise_if_low_memory self.error_threshold)) ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node LAPTOP-8F8GNOLG is used (15.82 / 15.86 GB). The top 10 memory consumers are: PID MEM COMMAND 22468 1.73GiB D:\pycharm\PyCharm 2023.2.4\bin\pycharm64.exe E:\HOP 118016 0.77GiB D:\anaconda\envs\HOP\python.exe E:\HOP\msg_code\train.py 209800 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 16000 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 206356 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 205948 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 14156 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 20100 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208388 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208812 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py In addition, up to 0.0 GiB of shared memory is currently being used by the Ray object store. --- --- Tip: Use the `ray memory` command to list active objects in the cluster. --- To disable OOM exceptions, set RAY_DISABLE_MEMORY_MONITOR=1. --- 2024-12-09 14:20:48,309 ERROR worker.py:85 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::RolloutWorker.set_weights() (pid=20100, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000017E5B52D788>) File "python\ray\_raylet.pyx", line 585, in ray._raylet.execute_task File "D:\anaconda\envs\HOP\lib\site-packages\ray\_private\memory_monitor.py", line 158, in raise_if_low_memory self.error_threshold)) ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node LAPTOP-8F8GNOLG is used (15.79 / 15.86 GB). The top 10 memory consumers are: PID MEM COMMAND 22468 1.73GiB D:\pycharm\PyCharm 2023.2.4\bin\pycharm64.exe E:\HOP 118016 0.77GiB D:\anaconda\envs\HOP\python.exe E:\HOP\msg_code\train.py 209800 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 16000 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 206356 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 205948 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 14156 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 20100 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208388 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208812 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py In addition, up to 0.0 GiB of shared memory is currently being used by the Ray object store. --- --- Tip: Use the `ray memory` command to list active objects in the cluster. --- To disable OOM exceptions, set RAY_DISABLE_MEMORY_MONITOR=1. --- 2024-12-09 14:20:48,315 ERROR worker.py:85 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::RolloutWorker.set_weights() (pid=209800, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001EAA44424C8>) File "python\ray\_raylet.pyx", line 585, in ray._raylet.execute_task File "D:\anaconda\envs\HOP\lib\site-packages\ray\_private\memory_monitor.py", line 158, in raise_if_low_memory self.error_threshold)) ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node LAPTOP-8F8GNOLG is used (15.79 / 15.86 GB). The top 10 memory consumers are: PID MEM COMMAND 22468 1.73GiB D:\pycharm\PyCharm 2023.2.4\bin\pycharm64.exe E:\HOP 118016 0.77GiB D:\anaconda\envs\HOP\python.exe E:\HOP\msg_code\train.py 209800 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 16000 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 206356 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 205948 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 14156 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 20100 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208388 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208812 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py In addition, up to 0.0 GiB of shared memory is currently being used by the Ray object store. --- --- Tip: Use the `ray memory` command to list active objects in the cluster. --- To disable OOM exceptions, set RAY_DISABLE_MEMORY_MONITOR=1. --- 2024-12-09 14:20:48,444 ERROR worker.py:85 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::RolloutWorker.set_weights() (pid=206356, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000027AF9C93308>) File "python\ray\_raylet.pyx", line 585, in ray._raylet.execute_task File "D:\anaconda\envs\HOP\lib\site-packages\ray\_private\memory_monitor.py", line 158, in raise_if_low_memory self.error_threshold)) ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node LAPTOP-8F8GNOLG is used (15.79 / 15.86 GB). The top 10 memory consumers are: PID MEM COMMAND 22468 1.73GiB D:\pycharm\PyCharm 2023.2.4\bin\pycharm64.exe E:\HOP 118016 0.77GiB D:\anaconda\envs\HOP\python.exe E:\HOP\msg_code\train.py 209800 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 16000 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 206356 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 205948 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 14156 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 20100 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208388 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208812 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py In addition, up to 0.0 GiB of shared memory is currently being used by the Ray object store. --- --- Tip: Use the `ray memory` command to list active objects in the cluster. --- To disable OOM exceptions, set RAY_DISABLE_MEMORY_MONITOR=1. --- 2024-12-09 14:20:48,457 ERROR worker.py:85 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::RolloutWorker.set_weights() (pid=205948, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000002C12E612488>) File "python\ray\_raylet.pyx", line 585, in ray._raylet.execute_task File "D:\anaconda\envs\HOP\lib\site-packages\ray\_private\memory_monitor.py", line 158, in raise_if_low_memory self.error_threshold)) ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node LAPTOP-8F8GNOLG is used (15.77 / 15.86 GB). The top 10 memory consumers are: PID MEM COMMAND 22468 1.73GiB D:\pycharm\PyCharm 2023.2.4\bin\pycharm64.exe E:\HOP 118016 0.77GiB D:\anaconda\envs\HOP\python.exe E:\HOP\msg_code\train.py 209800 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 16000 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 206356 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 205948 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 14156 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 20100 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208388 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208812 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py In addition, up to 0.0 GiB of shared memory is currently being used by the Ray object store. --- --- Tip: Use the `ray memory` command to list active objects in the cluster. --- To disable OOM exceptions, set RAY_DISABLE_MEMORY_MONITOR=1. --- 2024-12-09 14:20:48,528 ERROR worker.py:85 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::RolloutWorker.set_weights() (pid=14156, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000002648690E708>) File "python\ray\_raylet.pyx", line 585, in ray._raylet.execute_task File "D:\anaconda\envs\HOP\lib\site-packages\ray\_private\memory_monitor.py", line 158, in raise_if_low_memory self.error_threshold)) ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node LAPTOP-8F8GNOLG is used (15.84 / 15.86 GB). The top 10 memory consumers are: PID MEM COMMAND 22468 1.73GiB D:\pycharm\PyCharm 2023.2.4\bin\pycharm64.exe E:\HOP 118016 0.77GiB D:\anaconda\envs\HOP\python.exe E:\HOP\msg_code\train.py 209800 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 16000 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 206356 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 205948 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 14156 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 20100 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208388 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208812 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py In addition, up to 0.0 GiB of shared memory is currently being used by the Ray object store. --- --- Tip: Use the `ray memory` command to list active objects in the cluster. --- To disable OOM exceptions, set RAY_DISABLE_MEMORY_MONITOR=1. --- 2024-12-09 14:20:48,532 ERROR worker.py:85 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::RolloutWorker.set_weights() (pid=208812, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000223BEFDF6C8>) File "python\ray\_raylet.pyx", line 585, in ray._raylet.execute_task File "D:\anaconda\envs\HOP\lib\site-packages\ray\_private\memory_monitor.py", line 158, in raise_if_low_memory self.error_threshold)) ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node LAPTOP-8F8GNOLG is used (15.83 / 15.86 GB). The top 10 memory consumers are: PID MEM COMMAND 22468 1.73GiB D:\pycharm\PyCharm 2023.2.4\bin\pycharm64.exe E:\HOP 118016 0.77GiB D:\anaconda\envs\HOP\python.exe E:\HOP\msg_code\train.py 209800 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 16000 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 206356 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 205948 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 14156 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 20100 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208388 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208812 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py In addition, up to 0.0 GiB of shared memory is currently being used by the Ray object store. --- --- Tip: Use the `ray memory` command to list active objects in the cluster. --- To disable OOM exceptions, set RAY_DISABLE_MEMORY_MONITOR=1. --- Traceback (most recent call last): File "E:\HOP\msg_code\train.py", line 257, in <module> result=a3c_trainer.train() File "D:\anaconda\envs\HOP\lib\site-packages\ray\tune\trainable.py", line 314, in train result = self.step() File "D:\anaconda\envs\HOP\lib\site-packages\ray\rllib\agents\trainer.py", line 880, in step raise e File "D:\anaconda\envs\HOP\lib\site-packages\ray\rllib\agents\trainer.py", line 867, in step result = self.step_attempt() File "D:\anaconda\envs\HOP\lib\site-packages\ray\rllib\agents\trainer.py", line 920, in step_attempt step_results = next(self.train_exec_impl) File "D:\anaconda\envs\HOP\lib\site-packages\ray\util\iter.py", line 756, in __next__ return next(self.built_iterator) File "D:\anaconda\envs\HOP\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach for item in it: File "D:\anaconda\envs\HOP\lib\site-packages\ray\util\iter.py", line 843, in apply_filter for item in it: File "D:\anaconda\envs\HOP\lib\site-packages\ray\util\iter.py", line 843, in apply_filter for item in it: File "D:\anaconda\envs\HOP\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach for item in it: File "D:\anaconda\envs\HOP\lib\site-packages\ray\util\iter.py", line 828, in add_wait_hooks item = next(it) File "D:\anaconda\envs\HOP\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach for item in it: File "D:\anaconda\envs\HOP\lib\site-packages\ray\util\iter.py", line 529, in base_iterator actor_set.init_actors() File "D:\anaconda\envs\HOP\lib\site-packages\ray\util\iter.py", line 1237, in init_actors ray.get([a.par_iter_init.remote(self.transforms) for a in self.actors]) File "D:\anaconda\envs\HOP\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper return func(*args, **kwargs) File "D:\anaconda\envs\HOP\lib\site-packages\ray\worker.py", line 1713, in get raise value.as_instanceof_cause() ray.exceptions.RayTaskError(RayOutOfMemoryError): ray::RolloutWorker.par_iter_init() (pid=208388, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001D3D9F815C8>) File "python\ray\_raylet.pyx", line 585, in ray._raylet.execute_task File "D:\anaconda\envs\HOP\lib\site-packages\ray\_private\memory_monitor.py", line 158, in raise_if_low_memory self.error_threshold)) ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node LAPTOP-8F8GNOLG is used (15.61 / 15.86 GB). The top 10 memory consumers are: PID MEM COMMAND 22468 1.73GiB D:\pycharm\PyCharm 2023.2.4\bin\pycharm64.exe E:\HOP 118016 0.77GiB D:\anaconda\envs\HOP\python.exe E:\HOP\msg_code\train.py 14156 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 206356 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 209800 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208812 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 16000 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 205948 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 20100 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py 208388 0.61GiB D:\anaconda\envs\HOP\python.exe D:\anaconda\envs\HOP\lib\site-packages\ray\workers/default_worker.py In addition, up to 0.0 GiB of shared memory is currently being used by the Ray object store. --- --- Tip: Use the `ray memory` command to list active objects in the cluster. --- To disable OOM exceptions, set RAY_DISABLE_MEMORY_MONITOR=1. --- 进程已结束，退出代码为 1
```

# Codes

```python

```

# Solutions
